### ISSUE TITLE
[Feature request] Add simple HTTP API server like in llama.cpp with api like OpenAI 

### ISSUE THREAD

**Issue by pythops** [google/gemma.cpp#1]
For more infos here
https://github.com/ggerganov/llama.cpp/blob/master/examples/server/README.md

**Comment by austinvhuang** [comment]
Great suggestion, if there's others who interested please +emoji above and we'll prioritize this :)

**Comment by pythops** [comment]
Just for the update: `llama.cpp` added support for `gemma` models
https://github.com/ggerganov/llama.cpp/pull/5631

**Comment by loretoparisi** [comment]
> Just for the update: `llama.cpp` added support for `gemma` models
> 
> https://github.com/ggerganov/llama.cpp/pull/5631
> 
> 

Also with 💎Gemma in 🦙Llama.CPP you get CUDA, Neon and AMD GPUs support!

**Comment by omkar806** [comment]
adding a api like support would be great these models can be used on cpu for smaller tasks.
+1 for this.

**Comment by zeerd** [comment]
I have a question: why using http but not websocket?

As I known, the answer token is generated one word by one word. 
And, seems, http has no function to do multi-responses for one call.
Which means , http need to gather the whole answer before trans it back.

**Comment by ufownl** [comment]
> I have a question: why using http but not websocket?
> 
> As I known, the answer token is generated one word by one word. And, seems, http has no function to do multi-responses for one call. Which means , http need to gather the whole answer before trans it back.

WebSocket is more suitable for instant messenger style UI but may not be ideal for other UI types. And I think it is better to integrate gemma.cpp as a module into the web backend framework than to implement the HTTP/WebSocket API directly.

**Comment by Gopi-Uppari** [comment]
Could you please confirm if this issue is resolved for you with the above comment ? Please feel free to close the issue if it is resolved ?

Thank you.

**Comment by Gopi-Uppari** [comment]
Closing this issue, please feel free reopen if this is still a valid request. Thank you!
