### ISSUE TITLE
This Project is for learning purposes and not for sale

### ISSUE THREAD

**Issue by Zeenat30** [google/gemma.cpp#100]
Who ever signed the comittment this is my vertex Ai , my API my license being used and I am footing the bill and you are benefiting ... You are all complicit of theft of my license and console usage inclusive of the vertex AI.
The 50/50 split you decided to pursue after using bots and every way possible to keep the application and run it on my console is a screenshot for proof of intellectual theft . 

The work you have done you have published for commercial gain if you wish to do such work pay for it and do it without my consoles and licensed and AI software

**Comment by jan-wassenberg** [comment]
Hi, as far as I am aware, this Github repo does not contain nor use API keys. I am also unaware of any "50/50 split".

**Comment by Zeenat30** [comment]
I was using it to build a project in have screen shots of the api keys pulled from my profile regardless of the docs when I have time I will submit the proof and disable the api

**Comment by Zeenat30** [comment]
![Screenshot_20240314_215353_Chrome](https://github.com/google/gemma.cpp/assets/21279724/3b561a70-96b9-43e7-adf3-3a0fbd188c3c)
![Screenshot_20240311_222016_Chrome](https://github.com/google/gemma.cpp/assets/21279724/b54f0fdc-20e0-4726-9a4b-2cb538c031a6)
![Screenshot_20240311_215650_Chrome](https://github.com/google/gemma.cpp/assets/21279724/3975beab-7a70-46bb-8ffb-88910ddd5c4e)
