### ISSUE TITLE
Using mingw64 build on windows 10 fails

### ISSUE THREAD

**Issue by cnbac** [google/gemma.cpp#101]
Hello
My build fails using mingw64 on windows
Can you help me?
Thanks
Command used:
cmake -G "MinGW Makefiles" -B build
![image](https://github.com/google/gemma.cpp/assets/87373326/1547b031-e69d-4105-af6e-f2797ca3b61f)

cmake --preset make -G "MinGW Makefiles"
![image](https://github.com/google/gemma.cpp/assets/87373326/bdb1a162-b620-4a7d-9859-4479231856a2)

cmake --build --preset make -j 2
![image](https://github.com/google/gemma.cpp/assets/87373326/78c5b7e6-a234-45e9-b716-2d17933f45a3)

![image](https://github.com/google/gemma.cpp/assets/87373326/b6b58e03-985f-490b-86ae-d597a3118c9d)

cmake --build --preset make -j 2
[  2%] Building CXX object _deps/highway-build/CMakeFiles/hwy.dir/hwy/aligned_allocator.cc.obj
[  5%] Building CXX object _deps/sentencepiece-build/src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/arena.cc.obj
[  5%] Building CXX object _deps/highway-build/CMakeFiles/hwy.dir/hwy/nanobenchmark.cc.obj
[  5%] Building CXX object _deps/sentencepiece-build/src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/arenastring.cc.obj
[  8%] Building CXX object _deps/sentencepiece-build/src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/bytestream.cc.obj
[  8%] Building CXX object _deps/sentencepiece-build/src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/coded_stream.cc.obj
[ 11%] Building CXX object _deps/highway-build/CMakeFiles/hwy.dir/hwy/per_target.cc.obj
[ 14%] Building CXX object _deps/sentencepiece-build/src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/common.cc.obj
[ 14%] Building CXX object _deps/sentencepiece-build/src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/extension_set.cc.obj
[ 14%] Building CXX object _deps/highway-build/CMakeFiles/hwy.dir/hwy/print.cc.obj
[ 14%] Building CXX object _deps/highway-build/CMakeFiles/hwy.dir/hwy/targets.cc.obj
[ 17%] Building CXX object _deps/highway-build/CMakeFiles/hwy.dir/hwy/timer.cc.obj
[ 17%] Building CXX object _deps/sentencepiece-build/src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/generated_enum_util.cc.obj
[ 20%] Building CXX object _deps/sentencepiece-build/src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/generated_message_table_driven_lite.cc.obj
[ 20%] Linking CXX static library libhwy.a
[ 20%] Built target hwy
[ 20%] Building CXX object _deps/sentencepiece-build/src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/generated_message_util.cc.obj
[ 20%] Building CXX object _deps/highway-build/CMakeFiles/hwy_contrib.dir/hwy/contrib/sort/vqsort_128a.cc.obj
[ 23%] Building CXX object _deps/sentencepiece-build/src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/implicit_weak_message.cc.obj
[ 23%] Building CXX object _deps/sentencepiece-build/src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/int128.cc.obj
[ 23%] Building CXX object _deps/sentencepiece-build/src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/io_win32.cc.obj
[ 26%] Building CXX object _deps/sentencepiece-build/src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/message_lite.cc.obj
[ 26%] Building CXX object _deps/sentencepiece-build/src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/parse_context.cc.obj
[ 29%] Building CXX object _deps/sentencepiece-build/src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/repeated_field.cc.obj
[ 29%] Building CXX object _deps/sentencepiece-build/src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/status.cc.obj
[ 32%] Building CXX object _deps/sentencepiece-build/src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/statusor.cc.obj
[ 32%] Building CXX object _deps/sentencepiece-build/src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/stringpiece.cc.obj
[ 32%] Building CXX object _deps/sentencepiece-build/src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/stringprintf.cc.obj
[ 35%] Building CXX object _deps/sentencepiece-build/src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/structurally_valid.cc.obj
[ 35%] Building CXX object _deps/sentencepiece-build/src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/strutil.cc.obj
[ 38%] Building CXX object _deps/sentencepiece-build/src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/time.cc.obj
[ 41%] Building CXX object _deps/highway-build/CMakeFiles/hwy_contrib.dir/hwy/contrib/sort/vqsort_128d.cc.obj
[ 41%] Building CXX object _deps/sentencepiece-build/src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/wire_format_lite.cc.obj
[ 44%] Building CXX object _deps/sentencepiece-build/src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/zero_copy_stream.cc.obj
[ 44%] Building CXX object _deps/sentencepiece-build/src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/zero_copy_stream_impl.cc.obj
[ 44%] Building CXX object _deps/sentencepiece-build/src/CMakeFiles/sentencepiece-static.dir/__/third_party/protobuf-lite/zero_copy_stream_impl_lite.cc.obj
[ 47%] Building CXX object _deps/sentencepiece-build/src/CMakeFiles/sentencepiece-static.dir/builtin_pb/sentencepiece.pb.cc.obj
[ 47%] Building CXX object _deps/sentencepiece-build/src/CMakeFiles/sentencepiece-static.dir/builtin_pb/sentencepiece_model.pb.cc.obj
[ 50%] Building CXX object _deps/sentencepiece-build/src/CMakeFiles/sentencepiece-static.dir/bpe_model.cc.obj
[ 50%] Building CXX object _deps/sentencepiece-build/src/CMakeFiles/sentencepiece-static.dir/char_model.cc.obj
[ 52%] Building CXX object _deps/sentencepiece-build/src/CMakeFiles/sentencepiece-static.dir/error.cc.obj
[ 52%] Building CXX object _deps/highway-build/CMakeFiles/hwy_contrib.dir/hwy/contrib/sort/vqsort_f16a.cc.obj
[ 52%] Building CXX object _deps/sentencepiece-build/src/CMakeFiles/sentencepiece-static.dir/filesystem.cc.obj
[ 52%] Building CXX object _deps/sentencepiece-build/src/CMakeFiles/sentencepiece-static.dir/model_factory.cc.obj
[ 55%] Building CXX object _deps/sentencepiece-build/src/CMakeFiles/sentencepiece-static.dir/model_interface.cc.obj
[ 58%] Building CXX object _deps/highway-build/CMakeFiles/hwy_contrib.dir/hwy/contrib/sort/vqsort_f16d.cc.obj
[ 58%] Building CXX object _deps/sentencepiece-build/src/CMakeFiles/sentencepiece-static.dir/normalizer.cc.obj
[ 61%] Building CXX object _deps/sentencepiece-build/src/CMakeFiles/sentencepiece-static.dir/sentencepiece_processor.cc.obj
[ 61%] Building CXX object _deps/highway-build/CMakeFiles/hwy_contrib.dir/hwy/contrib/sort/vqsort_f32a.cc.obj
[ 61%] Building CXX object _deps/sentencepiece-build/src/CMakeFiles/sentencepiece-static.dir/unigram_model.cc.obj
[ 64%] Building CXX object _deps/sentencepiece-build/src/CMakeFiles/sentencepiece-static.dir/util.cc.obj
[ 64%] Building CXX object _deps/sentencepiece-build/src/CMakeFiles/sentencepiece-static.dir/word_model.cc.obj
[ 64%] Building CXX object _deps/sentencepiece-build/src/CMakeFiles/sentencepiece-static.dir/__/third_party/absl/flags/flag.cc.obj
[ 67%] Linking CXX static library libsentencepiece.a
[ 67%] Built target sentencepiece-static
[ 70%] Building CXX object _deps/highway-build/CMakeFiles/hwy_contrib.dir/hwy/contrib/sort/vqsort_f32d.cc.obj
[ 70%] Building CXX object _deps/highway-build/CMakeFiles/hwy_contrib.dir/hwy/contrib/sort/vqsort_f64a.cc.obj
[ 70%] Building CXX object _deps/highway-build/CMakeFiles/hwy_contrib.dir/hwy/contrib/sort/vqsort_f64d.cc.obj
[ 73%] Building CXX object _deps/highway-build/CMakeFiles/hwy_contrib.dir/hwy/contrib/sort/vqsort_i16a.cc.obj
[ 73%] Building CXX object _deps/highway-build/CMakeFiles/hwy_contrib.dir/hwy/contrib/sort/vqsort_i16d.cc.obj
[ 76%] Building CXX object _deps/highway-build/CMakeFiles/hwy_contrib.dir/hwy/contrib/sort/vqsort_i32a.cc.obj
[ 76%] Building CXX object _deps/highway-build/CMakeFiles/hwy_contrib.dir/hwy/contrib/sort/vqsort_i32d.cc.obj
[ 79%] Building CXX object _deps/highway-build/CMakeFiles/hwy_contrib.dir/hwy/contrib/sort/vqsort_i64a.cc.obj
[ 79%] Building CXX object _deps/highway-build/CMakeFiles/hwy_contrib.dir/hwy/contrib/sort/vqsort_i64d.cc.obj
[ 79%] Building CXX object _deps/highway-build/CMakeFiles/hwy_contrib.dir/hwy/contrib/sort/vqsort_kv128a.cc.obj
[ 82%] Building CXX object _deps/highway-build/CMakeFiles/hwy_contrib.dir/hwy/contrib/sort/vqsort_kv128d.cc.obj
[ 82%] Building CXX object _deps/highway-build/CMakeFiles/hwy_contrib.dir/hwy/contrib/sort/vqsort_kv64a.cc.obj
[ 85%] Building CXX object _deps/highway-build/CMakeFiles/hwy_contrib.dir/hwy/contrib/sort/vqsort_kv64d.cc.obj
[ 85%] Building CXX object _deps/highway-build/CMakeFiles/hwy_contrib.dir/hwy/contrib/sort/vqsort_u16a.cc.obj
[ 88%] Building CXX object _deps/highway-build/CMakeFiles/hwy_contrib.dir/hwy/contrib/sort/vqsort_u16d.cc.obj
[ 88%] Building CXX object _deps/highway-build/CMakeFiles/hwy_contrib.dir/hwy/contrib/sort/vqsort_u32a.cc.obj
[ 88%] Building CXX object _deps/highway-build/CMakeFiles/hwy_contrib.dir/hwy/contrib/sort/vqsort_u32d.cc.obj
[ 91%] Building CXX object _deps/highway-build/CMakeFiles/hwy_contrib.dir/hwy/contrib/sort/vqsort_u64a.cc.obj
[ 91%] Building CXX object _deps/highway-build/CMakeFiles/hwy_contrib.dir/hwy/contrib/sort/vqsort_u64d.cc.obj
[ 94%] Building CXX object _deps/highway-build/CMakeFiles/hwy_contrib.dir/hwy/contrib/image/image.cc.obj
[ 94%] Building CXX object _deps/highway-build/CMakeFiles/hwy_contrib.dir/hwy/contrib/sort/vqsort.cc.obj
[ 94%] Linking CXX static library libhwy_contrib.a
[ 94%] Built target hwy_contrib
[ 97%] Building CXX object CMakeFiles/gemma.dir/run.cc.obj
[ 97%] Building CXX object CMakeFiles/gemma.dir/gemma.cc.obj
[100%] Building CXX object CMakeFiles/gemma.dir/compression/blob_store.cc.obj
In file included from E:/code/ai/gemma/gppmain/gemma.cpp/build/_deps/highway-src/hwy/aligned_allocator.h:30,
                 from E:/code/ai/gemma/gppmain/gemma.cpp/compression/blob_store.h:24,
                 from E:/code/ai/gemma/gppmain/gemma.cpp/compression/compress-inl.h:27,
                 from E:/code/ai/gemma/gppmain/gemma.cpp/gemma.cc:25,
                 from E:/code/ai/gemma/gppmain/gemma.cpp/build/_deps/highway-src/hwy/foreach_target.h:72,
                 from E:\code\ai\gemma\gppmain\gemma.cpp\gemma.cc:22:
In function 'void hwy::CopyBytes(const From*, To*) [with long long unsigned int kBytes = 2; From = short unsigned int; To = unsigned char]',
    inlined from 'void hwy::N_AVX2::detail::AVX2UIF8Or16StoreTrailingN(hwy::N_AVX2::VFromD<D>, D, hwy::N_AVX2::TFromD<D>*, size_t) [with D = hwy::N_AVX2::Simd<unsigned char, 32, 0>; hwy::EnableIf<(sizeof (typename D::T) == 1)>* <anonymous> = 0]' at E:/code/ai/gemma/gppmain/gemma.cpp/build/_deps/highway-src/hwy/ops/x86_128-inl.h:7411:32,
    inlined from 'void hwy::N_AVX2::StoreN(VFromD<D>, D, TFromD<D>*, size_t) [with D = Simd<unsigned char, 32, 0>; hwy::EnableIf<(((long long unsigned int{1} << sizeof (typename D::T)) & ((1 << 1) | (1 << 2))) != 0)>* <anonymous> = 0; hwy::EnableIf<(D::kPrivateLanes > 2)>* <anonymous> = 0]' at E:/code/ai/gemma/gppmain/gemma.cpp/build/_deps/highway-src/hwy/ops/x86_128-inl.h:7460:39,
    inlined from 'static void gcpp::N_AVX2::SfpCodec::Enc(DF, const float*, size_t, gcpp::SfpStream*) [with DF = hwy::N_AVX2::Simd<float, 8, 0>; hwy::EnableIf<IsSame<typename hwy::RemoveConstT<typename hwy::RemoveVolatileT<typename hwy::RemoveRefT<typename D::T>::type>::type>::type, float>()>* <anonymous> = 0]' at E:/code/ai/gemma/gppmain/gemma.cpp/compression/sfp-inl.h:256:17,
    inlined from 'static void gcpp::N_AVX2::CompressTraits<gcpp::SfpStream>::Compress(DF, const float*, size_t, gcpp::CompressPerThread&, size_t, MatT*, size_t) [with DF = hwy::N_AVX2::Simd<float, 8, 0>; hwy::EnableIf<IsSame<typename hwy::RemoveConstT<typename hwy::RemoveVolatileT<typename hwy::RemoveRefT<typename D::T>::type>::type>::type, float>()>* <anonymous> = 0]' at E:/code/ai/gemma/gppmain/gemma.cpp/compression/compress-inl.h:238:18,
    inlined from 'gcpp::N_AVX2::Compress<gcpp::SfpStream>(const float*, size_t, gcpp::CompressWorkingSet&, size_t, gcpp::SfpStream*, size_t, hwy::ThreadPool&)::<lambda(uint32_t, size_t)>' at E:/code/ai/gemma/gppmain/gemma.cpp/compression/compress-inl.h:356:30:
E:/code/ai/gemma/gppmain/gemma.cpp/build/_deps/highway-src/hwy/base.h:313:19: warning: writing 2 bytes into a region of size 1 [-Wstringop-overflow=]
  313 |   __builtin_memcpy(to, from, kBytes);
      |   ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
In file included from E:/code/ai/gemma/gppmain/gemma.cpp/compression/compress.h:35,
                 from E:/code/ai/gemma/gppmain/gemma.cpp/compression/compress-inl.h:29:
E:/code/ai/gemma/gppmain/gemma.cpp/compression/sfp.h: In function 'gcpp::N_AVX2::Compress<gcpp::SfpStream>(const float*, size_t, gcpp::CompressWorkingSet&, size_t, gcpp::SfpStream*, size_t, hwy::ThreadPool&)::<lambda(uint32_t, size_t)>':
E:/code/ai/gemma/gppmain/gemma.cpp/compression/sfp.h:44:11: note: destination object 'gcpp::SfpStream::byte' of size 1
   44 |   uint8_t byte;
      |           ^~~~
[100%] Linking CXX executable gemma.exe
D:/soft/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\gemma.dir/objects.a(run.cc.obj):run.cc:(.text+0x5a68): undefined reference to `WakeByAddressAll'
D:/soft/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\gemma.dir/objects.a(run.cc.obj):run.cc:(.text+0x61e7): undefined reference to `WakeByAddressAll'
D:/soft/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\gemma.dir/objects.a(run.cc.obj):run.cc:(.text+0x629f): undefined reference to `WakeByAddressAll'
D:/soft/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\gemma.dir/objects.a(run.cc.obj):run.cc:(.text$_ZN3hwy10ThreadPool10ThreadFuncEyyPNS_7PoolMemE[_ZN3hwy10ThreadPool10ThreadFuncEyyPNS_7PoolMemE]+0xa3): undefined reference to `WaitOnAddress'
D:/soft/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\gemma.dir/objects.a(run.cc.obj):run.cc:(.text$_ZN3hwy10ThreadPoolD1Ev[_ZN3hwy10ThreadPoolD1Ev]+0x25): undefined reference to `WakeByAddressAll'
D:/soft/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\gemma.dir/objects.a(gemma.cc.obj):gemma.cc:(.text+0x2368b): undefined reference to `WakeByAddressAll'
D:/soft/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\gemma.dir/objects.a(gemma.cc.obj):gemma.cc:(.text+0x2384b): undefined reference to `WakeByAddressAll'
D:/soft/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\gemma.dir/objects.a(gemma.cc.obj):gemma.cc:(.text+0x239fb): undefined reference to `WakeByAddressAll'
D:/soft/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\gemma.dir/objects.a(gemma.cc.obj):gemma.cc:(.text+0x23bbb): undefined reference to `WakeByAddressAll'
D:/soft/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\gemma.dir/objects.a(gemma.cc.obj):gemma.cc:(.text+0x23d6b): more undefined references to `WakeByAddressAll' follow
collect2.exe: error: ld returned 1 exit status
mingw32-make[3]: *** [CMakeFiles\gemma.dir\build.make:137: gemma.exe] Error 1
mingw32-make[2]: *** [CMakeFiles\Makefile2:372: CMakeFiles/gemma.dir/all] Error 2
mingw32-make[1]: *** [CMakeFiles\Makefile2:379: CMakeFiles/gemma.dir/rule] Error 2
mingw32-make: *** [Makefile:188: gemma] Error 2

Thanks

**Comment by jan-wassenberg** [comment]
Hi, this [WakeByAddressAll function](https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-wakebyaddressall) may require some additional developer library installation. From that link: "Microsoft Store app developers may need to obtain synchronization.lib by installing the [Windows Software Development Kit (SDK)](https://developer.microsoft.com/windows/downloads/windows-sdk/)." You may need to add this synchronization.lib to the linker command line.

**Comment by cnbac** [comment]
> Hi, this [WakeByAddressAll function](https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-wakebyaddressall) may require some additional developer library installation. From that link: "Microsoft Store app developers may need to obtain synchronization.lib by installing the [Windows Software Development Kit (SDK)](https://developer.microsoft.com/windows/downloads/windows-sdk/)." You may need to add this synchronization.lib to the linker command line.

Thanks
After I executed
cmake -G "MinGW Makefiles" --preset make
after
Revise 
build\CMakeFiles\gemma.dir\link.txt

c++.exe -O3 -DNDEBUG -Wl,--whole-archive CMakeFiles\gemma.dir/objects.a -Wl,--no-whole-archive -lsynchronization -o gemma.exe -Wl,--out-implib,libgemma.dll.a -Wl,--major-image-version,0,--minor-image-version,0 @CMakeFiles\gemma.dir\linkLibs.rsp

Increase
-lsynchronization
Options

Execute again
cmake --build --preset make -j 3
build successful

**Comment by jan-wassenberg** [comment]
Glad to hear! Closing, feel free to reopen if there are other issues.
