### ISSUE TITLE
Is the format of output Markdown?

### ISSUE THREAD

**Issue by zeerd** [google/gemma.cpp#106]
It seems to be Markdown at most of time. But sometimes not.

Like below:

```
> Write a quatrain for star.  

[ Reading prompt ] ........

Twinkling bright,
Guiding lost souls through the night,
Sparkling, like a thousand eyes,
Illuminating the darkest skies.
```

Those lines will come to one line in a Markdown-Viewer.

**Comment by pkgoogle** [comment]
Hi @zeerd, As you have noted, sometimes markdown is provided, It's hard to say in the space of all outputs that all the outputs will be well formatted in Markdown but If the system produces code, generally that is formatted with Markdown. But I would say generally the expected output is just text.

**Comment by zeerd** [comment]
Thanks, unfortunately I can't easily present the answer well in my tool because of this.
