### ISSUE TITLE
How to compile this into the WASM?

### ISSUE THREAD

**Issue by yukiarimo** [google/gemma.cpp#13]

**Comment by jan-wassenberg** [comment]
Hi @yukiarimo , I believe no special action is required for this code, if you are able to build code for WASM, you are also able to build this for WASM.

If you use bazel for builds, it suffices to add `--config=wasm --features=wasm_simd` to the command line.

I am not as familiar with WASM using CMake, are the Emscripten docs helpful?

**Comment by yukiarimo** [comment]
Yeah, I would try. Emscripten docs are quite complex to read for me.

**Comment by jan-wassenberg** [comment]
Closing, please feel free to reopen if you'd like to discuss specifics :)

**Comment by tomayac** [comment]
> Yeah, I would try. Emscripten docs are quite complex to read for me.

The place you probably want to start looking is the [building projects](https://emscripten.org/docs/compiling/Building-Projects.html#building-projects) section.
