### ISSUE TITLE
again:Cached compressed weights does not exist yet gemma

### ISSUE THREAD

**Issue by zhjygit** [google/gemma.cpp#134]
My device is android phone, aarch64, with 8G ram, about 4.5G is idle and can be used.
I download archive.tar.gz from kaggle with 2b-it-sfp, tar -zxvf archive.tar.gz, i got 2b-it-sfp.sbs and tokenizer.spm.
And then git clone https://github.com/google/gemma.cpp.git
    cd gemma.cpp
    cd build    (build directory is blank)
    cmake ..
    make jemma

When i executed the code:
      ../gemma.cpp/build/gemma --model 2b-it --tokenizer tokenizer.spm --compressed_weights 2b-it-sfp.sbs
      the errors is as follow:Cached compressed weights does not exist yet (code 154), compressing weights and creating file: .//2b-it-sfp.sbs      
      sometimes, the error code is 232 instead 154.

**Comment by zhjygit** [comment]
my phone is aarch64

**Comment by jan-wassenberg** [comment]
Error numbers are line numbers inside blob_store.cc.
154 is lseek failing, 232 is file size not matching the expected size.
It seems something is going wrong with the device's IO. Is it Android r15c or later?
Did you download v3 of the weights? Their size has just changed.

**Comment by austinvhuang** [comment]
With the recent MQA change there was a window when artifact wasn’t in sync (using the kaggle client api code worked but the artifact download didn’t).

https://discord.com/channels/1212851822813904947/1212851825334550548/1225712866934521887

might try downloading again or checking if the kaggle client api works and see if it’s still an issue.

**Comment by jan-wassenberg** [comment]
Agree the download might be broken/partial, this would explain lseek failures.

> How can i know the version is Android r15c or later?

We can look at "About phone" in settings, that has an "Android version" which we can map to targetSdk(API level) using https://apilevels.com/.

**Comment by jan-wassenberg** [comment]
Any update on whether you are still seeing the issue?
