### ISSUE TITLE
Mismatch between expected 1024000 and actual 1024512 KiB size.

### ISSUE THREAD

**Issue by ticcky** [google/gemma.cpp#152]
I downloaded weigths from `https://huggingface.co/google/gemma-2b-cpp/blob/main/2b-pt.sbs` but can't make them run:

```
$ ./gemma --tokenizer ~/Downloads/gemma-2b-pt/tokenizer.spm --model 2b-it --weights ~/Downloads/gemma-2b-pt/2b-pt.sbs 
Mismatch between expected 1024000 and actual 1024512 KiB size. Please see README.md on how to update the weights.
```

Am I missing some flags? I tried compiling with `cmake -B build -DWEIGHT_TYPE=hwy::bfloat16_t` but that didn't seem to have any effect.

**Comment by jan-wassenberg** [comment]
Sorry about the trouble. The weights have changed and they appear not to be synced across all sources. Are you able to download the v3 version from [Kaggle](https://www.kaggle.com/models/google/gemma/frameworks/gemmaCpp/variations/1.1-2b-it-sfp), or the model there prefixed with "1.1" which also contain the updated size?

**Comment by KumarGitesh2024** [comment]
Hi @ticcky , Could you please confirm, if the issue is resolved. If yes, please feel free to move this issue to closed status
