### ISSUE TITLE
Any more fine example or user-guide for CodeGemma?

### ISSUE THREAD

**Issue by zeerd** [google/gemma.cpp#153]
I tried something like this:

```
main.c <|fim_prefix|>// Read two numbers from parameter and output there sum <|fim_suffix|> \n <|fim_middle|>
```

It returns below, which looks no bad.

```
<|fim_middle|>#include <stdio.h> 
int main() 
  int a,b; 
  scanf("%d %d",&a,&b); 
  printf("%d",a+b); 
  return 0; 
} 
// Output: 10
```

But, most of the time, it returns something repeatedly endless. For example, Send:

```
main.c <|fim_prefix|>int main()
{
  int a,b;
  // read numbers from cmdline parameters
   <|fim_suffix|> 
  scanf("%d %d",&a,&b);
  printf("%d",a+b);
  return 0;
}
 <|fim_middle|>
```

It returns thing below repeatedly:

```
<|fim_middle|>("%d %d",&a,&b);
  printf("%d",a+b);
  return 0;
  // read numbers from cmdline parameters
   scanf("%d %d",&a,&b);
  printf("%d",a+b);
  return 0;
  // read numbers from cmdline parameters
  scanf("%d %d",&a,&b);
  printf("%d",a+b);
  return 0;
  // read numbers from cmdline parameters

...

```

I am not sure if I am using the key-words like `<|fim_prefix|>` , `<|fim_suffix|>` , `<|fim_middle|>` in the right way.

```
Using 2b-pt-sfp for the tests above.
```

**Comment by jan-wassenberg** [comment]
Hi, sorry to reply late. There is some documentation on how FIM works here: https://huggingface.co/google/codegemma-7b

One thing to watch out for is the whitespace: neither too much, nor too little. You probably want \n to end the comment before fim_suffix, which is where the model would insert. But maybe skip the other whitespace around fim_suffix.

You might also have more luck with the 7b-it (instruction tuned) model if that's an option?
