### ISSUE TITLE
How can I get the compiled static executable binary file in linux platform?

### ISSUE THREAD

**Issue by lnxknl** [google/gemma.cpp#161]
I want to run this model in limited internet env, so I want to get this executable binary file.

**Comment by xinpingwang** [comment]
I made some changes to the cmake build file, so that the build result is portable. maybe you can wait for #168 to be merged or changed locally to have a try.

**Comment by jan-wassenberg** [comment]
Thanks @xinpingwang , I think your change plus `set(BUILD_SHARED_LIBS OFF)
set(CMAKE_EXE_LINKER_FLAGS "-static")` is sufficient :)
Please feel free to reopen if you'd like to discuss further.
