### ISSUE TITLE
Paligemma Support

### ISSUE THREAD

**Issue by okpatil4u** [google/gemma.cpp#185]
Are you planning to integrate Paligemma ?

**Comment by jan-wassenberg** [comment]
Thanks for reaching out! Paligemma is in-scope, but not yet on our near-term roadmap. It will take us a while to get there, but we'd be happy to collaborate with anyone interested to make it happen faster :)

**Comment by MathiasSchindler** [comment]
@jan-wassenberg As far as I can see, the PaliGemma support is currently only in the dev branch, not in main. Is there a release schedule or any indication about the main branch?

**Comment by jan-wassenberg** [comment]
Right, we push to the main branch at irregular intervals. We can certainly do that soon If it would be helpful?
