### ISSUE TITLE
Compilation fails for raspberry pi 

### ISSUE THREAD

**Issue by EphemeralSapient** [google/gemma.cpp#197]
Issue : Failed to compile using bazel and make [ followed the instruction ]

- Bazel Log : [bazel_compile_log.txt](https://github.com/google/gemma.cpp/files/15447458/bazel_compile_log.txt)

- Make Log : [make_log.txt](https://github.com/google/gemma.cpp/files/15447471/make_log.txt)

 Architecture : ARM64 

 OS : Ubuntu 24.04 [noble]

 It's my first time creating an issue on github; sorry if I've missed anything important

**Comment by jan-wassenberg** [comment]
Hi, thanks for reporting :) This is already fixed in the dev branch, we'll be updating the main branch soon.
