### ISSUE TITLE
Run 7b model error,"./gemma --tokenizer tokenizer.spm --model 7b-it --compressed_weights 7b-it.sbs" ,error message: "Failed to read cache gating_ein_0 (error 294)"

### ISSUE THREAD

**Issue by lnxknl** [google/gemma.cpp#20]
Failed to read cache gating_ein_0 (error 294)                      │
Abort at /home/.../models/gemma.cpp/./gemma.cc:117: Failed│
 to open model file  - does it exist?                              │

**Comment by jan-wassenberg** [comment]
Hi, please see #5, does that help?

**Comment by cerisara** [comment]
Yes it does, hanks ! That's indeed the cmake option to solve this error:
```
cmake -DWEIGHT_TYPE=hwy::bfloat16_t ..
```

**Comment by lnxknl** [comment]
k

> Yes it does, hanks ! That's indeed the cmake option to solve this error:
> 
> ```
> cmake -DWEIGHT_TYPE=hwy::bfloat16_t ..
> ```

yes, compile with this cmake opition wihtout this error.
