### ISSUE TITLE
Android aarch64 support

### ISSUE THREAD

**Issue by Code-keys** [google/gemma.cpp#21]
is this support Android aarch64? 
or Android Studio? 
or AOSP ? 

It  seems easy!  aha

**Comment by jan-wassenberg** [comment]
Yes, we have successfully built and tested on aarch64 Android. I believe even Armv7 would work.

**Comment by Code-keys** [comment]
3Q

**Comment by windmaple** [comment]
Works fine with Termux

![Uploading WechatIMG171.jpg…]()

**Comment by Code-keys** [comment]
> Yes, we have successfully built and tested on aarch64 Android. I believe even Armv7 would work.

There the bash/step released ?

**Comment by jan-wassenberg** [comment]
What do you mean by bash/step? :)

**Comment by Code-keys** [comment]
Cross-compiled script

**Comment by jan-wassenberg** [comment]
Ah, you are asking for the command line to use?
For armv7 try `CC=arm-linux-gnueabihf-gcc-11 CXX=arm-linux-gnueabihf-g++-11 cmake .. -DHWY_CMAKE_ARM7:BOOL=ON`. For aarch64 it's just `CC=aarch64-linux-gnu-gcc-11 CXX=aarch64-linux-gnu-g++-11 cmake ..`.

**Comment by Code-keys** [comment]
3Q，I got it

**Comment by nonetrix** [comment]
> Works fine with Termux

Not for me personally

![Image](https://github.com/user-attachments/assets/23b0b11c-5b33-4881-b58c-59af2c93f935)

**Comment by jan-wassenberg** [comment]
Thanks for reporting :) What compiler is that?
I think a newer compiler ought to be able to handle this.
Another alternative is to build with something like `-march=armv8.5-a+sve`, assuming your CPU support SVE.
