### ISSUE TITLE
make error on RaspberryPi 4

### ISSUE THREAD

**Issue by StudyingLover** [google/gemma.cpp#25]
I am using raspberry pi 4 , os is raspberry os ,aarch64 .

When I run `make -2 gemma`, I got a mistake. The whole logs are as follows, so long so I create a file and storge the log into it, you can download the log file from the url.

https://cdn.studyinglover.com/pic/2024/02/abf1e1cfb9c7625a8ab7764ad4baaa74.log

**Comment by jan-wassenberg** [comment]
Thanks for letting us know. We made a mistake (missing some hn:: prefixes), it still worked on x86 due to argument-dependent lookup but not on SVE, as you have found. Fix is on the way.

**Comment by StudyingLover** [comment]
I build gemma again, but meet a mistake again 
```
In file included from /home/pi/gemma/gemma.cpp/run.cc:28:
/home/pi/gemma/gemma.cpp/gemma.h:36:10: fatal error: sentencepiece_processor.h: No such file or directory
   36 | #include "sentencepiece_processor.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [CMakeFiles/gemma.dir/build.make:76: CMakeFiles/gemma.dir/run.cc.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from /home/pi/gemma/gemma.cpp/./gemma.cc:59,
                 from /home/pi/gemma/gemma.cpp/build/_deps/highway-src/hwy/foreach_target.h:163,
                 from /home/pi/gemma/gemma.cpp/gemma.cc:22:
/home/pi/gemma/gemma.cpp/./gemma.h:36:10: fatal error: sentencepiece_processor.h: No such file or directory
   36 | #include "sentencepiece_processor.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [CMakeFiles/gemma.dir/build.make:90: CMakeFiles/gemma.dir/gemma.cc.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:377: CMakeFiles/gemma.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:384: CMakeFiles/gemma.dir/rule] Error 2
make: *** [Makefile:189: gemma] Error 2
```

I'm curious why the #include "src/sentencepiece_processor.h" from the main branch is being changed to #include "sentencepiece_processor.h".

**Comment by dan-zheng** [comment]
> I build gemma(from dev branch) again, but meet a mistake again
> 
> ```
> In file included from /home/pi/gemma/gemma.cpp/run.cc:28:
> /home/pi/gemma/gemma.cpp/gemma.h:36:10: fatal error: sentencepiece_processor.h: No such file or directory
>    36 | #include "sentencepiece_processor.h"
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> make[3]: *** [CMakeFiles/gemma.dir/build.make:76: CMakeFiles/gemma.dir/run.cc.o] Error 1
> make[3]: *** Waiting for unfinished jobs....
> In file included from /home/pi/gemma/gemma.cpp/./gemma.cc:59,
>                  from /home/pi/gemma/gemma.cpp/build/_deps/highway-src/hwy/foreach_target.h:163,
>                  from /home/pi/gemma/gemma.cpp/gemma.cc:22:
> /home/pi/gemma/gemma.cpp/./gemma.h:36:10: fatal error: sentencepiece_processor.h: No such file or directory
>    36 | #include "sentencepiece_processor.h"
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> make[3]: *** [CMakeFiles/gemma.dir/build.make:90: CMakeFiles/gemma.dir/gemma.cc.o] Error 1
> make[2]: *** [CMakeFiles/Makefile2:377: CMakeFiles/gemma.dir/all] Error 2
> make[1]: *** [CMakeFiles/Makefile2:384: CMakeFiles/gemma.dir/rule] Error 2
> make: *** [Makefile:189: gemma] Error 2
> ```

Thanks for reporting, fixing this now.
