### ISSUE TITLE
RecurrentGemma 9b support

### ISSUE THREAD

**Issue by fizzAI** [google/gemma.cpp#252]
Hi!
Are there currently any plans to support the [9b version of RecurrentGemma](https://huggingface.co/google/recurrentgemma-9b) that recently released?

**Comment by pculliton** [comment]
Hi! We do have plans to support RecurrentGemma 9b. There is some internal work to be done - I think it's likely that we'll be able to release it around the end of June. If contributors want to help, we could definitely use help with:
- Adding a recurrent 9b configuration to `convert_weights.py` (and `configs.h`)
- Testing that the configuration works with the output of `convert_weights.py`
- Letting us know if it does not work.

This would save us some time in launching it! Thanks for raising this issue.

**Comment by Gopi-Uppari** [comment]
Hi @fizzAI,

Could you please confirm if this issue is resolved for you with the above comment ? Please feel free to close the issue if it is resolved ?

Thank you.

**Comment by Gopi-Uppari** [comment]
Hi @fizzAI,

Could you please confirm if this issue is resolved for you with the above comment ? Please feel free to close the issue if it is resolved ?

Thank you.
