### ISSUE TITLE
The %C and %Q will not detected when eot_line = "other string"

### ISSUE THREAD

**Issue by ljcucc** [google/gemma.cpp#283]
When eot_line set to other string, then %C and %Q will not detected.

for example:

```sh
./gemma \                                                                                                                                          
    --tokenizer./tokenizer.spm \
    --model 9b-it  \
    --compressed_weights ./9b-it-sfp.sbs  \
    --multiturn 1 \
    --eot_line .
```

> reference: https://github.com/google/gemma.cpp/blob/8ac5d66575429c4fca19fb394c8926074352c766/gemma/run.cc#L129

at Line 129, the %C and %Q only detect prompt_string, but this will fail when eot_line set to something else.

**Comment by jan-wassenberg** [comment]
Thanks for reporting. If I understand correctly, the issue is: when !eot_string.empty(), we append \n, so the string does not match "%c". Fix coming shortly.
