### ISSUE TITLE
WSL support: "Killed", once executed on WSL 

### ISSUE THREAD

**Issue by Code-keys** [google/gemma.cpp#30]
**WSL subsystem**
anything seems normal, once executed,  only "**Killed**" print-out.
```
$  ./gemma  --tokenizer /home/home/F/GPT/Gemma/2b-it-cpp/tokenizer.spm \                                                     > --compressed_weights /home/home/F/GPT/Gemma/2b-it-cpp/2b-it.sbs \                                                                > --model 2b-it 
$  Killed
```
**ENV:**
clang-10.0
ubuntu18.04 && ubuntu20.04
cmake

**Comment by dannyvpm** [comment]
Looks like your machine is unable to support the 2B model.

**Comment by austinvhuang** [comment]
Hi @Code-keys , can you try with 2b-it-sfp.sbs? SFP uses compressed 8bit weights. also make sure to use the right build (if you use 2b-it vs. 2b-it-sfp there's a different set of build settings) - we've updated the README. Can you share any information about your hardware settings (RAM, etc.)?

**Comment by Code-keys** [comment]
i will have a try

**Comment by ledurnan** [comment]
I get this with the 7b model but not 2b. For me it's a memory limit issue. It seems to be killed when it runs out of RAM (8gb on my laptop) to store the 7b model.

A better error message would be helpful.

**Comment by Code-keys** [comment]
using the newest projects is fine, model (2b-pt)

**Comment by Code-keys** [comment]
The precision of 2b-it is nice, while the 2b-pt seems like a shit, so why?

**Comment by ledurnan** [comment]
> The precision of 2b-it is nice, while the 2b-pt seems like a shit, so why?

Because 2b-it is instruction tuned. 2b-pt is not. You're not comparing the same type of model.

**Comment by Code-keys** [comment]
The rootcase is  OOM, :100:
