### ISSUE TITLE
Convert recurrentgemma weights

### ISSUE THREAD

**Issue by 0wwafa** [google/gemma.cpp#301]
If I download google/recurrentgemma-2b-it  from HF, I get a directory with safetensors.
How do I convert it to the compressed file gemma.cpp wants?
How do I run an interference using gemma.cpp with that particular model?
(don't tell me to download the SBS from kaggle)
My question is about: google/recurrentgemma-2b-it and the similar 9b directory

**Comment by jan-wassenberg** [comment]
@fischbacher implemented conversion scripts from RecurrentGemma to  which are awaiting open-sourcing.

Downloading from Kaggle is currently the easiest/quickest path, I'm curious why that is not preferred?

**Comment by 0wwafa** [comment]
> @fischbacher implemented conversion scripts from RecurrentGemma to which are awaiting open-sourcing.
> 
> Downloading from Kaggle is currently the easiest/quickest path, I'm curious why that is not preferred?

because I already download the model and I am on a metered connection ;)

**Comment by jan-wassenberg** [comment]
Ah, that makes sense :) Hopefully the scripts can be open sourced soon.
