### ISSUE TITLE
macbook android studio compile error

### ISSUE THREAD

**Issue by isold23** [google/gemma.cpp#365]
C/C++: CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.

**Comment by jan-wassenberg** [comment]
Hi, please search for the error message. For example, https://stackoverflow.com/questions/38658014/ninja-not-found-by-cmake might help.

**Comment by isold23** [comment]
Android studio on macbook compile gemma.cpp

/Android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/array:143:18: error: array is too large (1179648000 elements)
    _Tp __elems_[_Size];

How to fix it?

**Comment by jan-wassenberg** [comment]
Unfortunately the way our code is structured, the per-layer weights are stored in std::array. This will not work on 32-bit x86 or armv7 targets, but we are seeing it work with recent compilers on aarch64. Are you able to update the NDK/Android Studio?

**Comment by isold23** [comment]
> Unfortunately the way our code is structured, the per-layer weights are stored in std::array. This will not work on 32-bit x86 or armv7 targets, but we are seeing it work with recent compilers on aarch64. Are you able to update the NDK/Android Studio?

Thanks！
<img width="965" alt="image" src="https://github.com/user-attachments/assets/f9b99501-66b1-4fba-baf4-af0a6b61a0d8">

**Comment by isold23** [comment]
<img width="1004" alt="image" src="https://github.com/user-attachments/assets/8ec703f3-d0f4-4322-b675-291a64265c7a">

xiaomi10 RAM 12G. Qualcomm865
The QueryModel function cannot return. Why is it not able to return?

**Comment by jan-wassenberg** [comment]
One likely cause is that 12G is not enough memory? Are you running the 2B?
We're not especially careful yet about allocating the KV cache. There's some work in progress on that, we might also change to bf16. In the meantime, you could try reducing the `kv_cache.seq_len` value - does that help?

**Comment by isold23** [comment]
I am currently running the 2B model. The default value for GEMMA_MAX_SEQLEN is 4096. I experienced the same issue when I set it to 3072; the application crashes when the value is set below 3072.

**Comment by jan-wassenberg** [comment]
Thanks, good to know. Are you able to attach a debugger (adb) or figure out via printf where the crash/freeze is?
Perhaps you might also want to try changing `bool use_spinning = true;` to false in gemma.h?

**Comment by Gopi-Uppari** [comment]
Hi @isold23,

Could you please confirm if this issue is resolved for you with the above comments ? Please feel free to close the issue if it is resolved ?

Thank you.

**Comment by Gopi-Uppari** [comment]
Closing this issue due to lack of recent activity, Please feel free reopen if this is still a valid request. Thank you!
