### ISSUE TITLE
Can we use gemma.cpp as a library in Android APP?

### ISSUE THREAD

**Issue by FranzKafkaYu** [google/gemma.cpp#370]
Hi Gemma developers,I want to use gemma.cpp as a library in Android system,is the source code compatiable with Android?Can I build with NDK?

**Comment by shubham0204** [comment]
Maybe issues #45 , #21 , #62 and [others listed](https://github.com/google/gemma.cpp/issues?q=is%3Aissue+android) here might help.

**Comment by KumarGitesh2024** [comment]
Hi FranzKafkaYu,
Have you tried the guided steps, is issue resolved? If yes, please feel free to move this issue to closed status.

**Comment by Gopi-Uppari** [comment]
Closing this issue due to lack of recent activity, Please feel free reopen if this is still a valid request. Thank you!
