### ISSUE TITLE
hwy/tests/mask_slide_test.cc.o error

### ISSUE THREAD

**Issue by cedricnew92** [google/gemma.cpp#384]
fatal error: error in backend: Cannot select: 0x7ff13bd2e6d0: v8i16 = X86ISD::VZEXT_MOVL 0x7ff13b8c2630, highway-src/hwy/ops/x86_128-inl.h:1446:23 @[ highway-src/hwy/ops/x86_128-inl.h:1468:10 @[ highway-src/hwy/ops/x86_128-inl.h:6192:19 @[ highway-src/hwy/ops/x86_128-inl.h:6229:23 @[ highway-src/hwy/tests/mask_combine_test.cc:61:38 ] ] ] ]
  0x7ff13b8c2630: v8i16 = bitcast 0x7ff13dcee220, highway-src/hwy/ops/x86_128-inl.h:2177:21 @[ highway-src/hwy/tests/mask_combine_test.cc:57:33 ]
    0x7ff13dcee220: v4i32 = scalar_to_vector 0x7ff13dcee700, highway-src/hwy/ops/x86_128-inl.h:2177:21 @[ highway-src/hwy/tests/mask_combine_test.cc:57:33 ]
      0x7ff13dcee700: i32,ch = load<(load (s16) from %ir.12, align 1, !alias.scope !377410, !noalias !377415), zext from i16> 0x7ff13bd2f028, 0x7ff13b8c1ad0, undef:i64, highway-src/hwy/base.h:340:3 @[ highway-src/hwy/ops/x86_128-inl.h:2176:3 @[ highway-src/hwy/tests/mask_combine_test.cc:57:33 ] ]
        0x7ff13b8c1ad0: i64,ch = CopyFromReg 0x7ff13ceaaf88, Register:i64 %1
          0x7ff0fd1f2830: i64 = Register %1
        0x7ff0fd1ef0e0: i64 = undef
In function: _ZN3hwy10N_AVX3_SPR29TestLowerAndUpperHalvesOfMaskclIaNS0_4SimdIaLm2ELi0EEEEEvT_T0_
clang: error: clang frontend command failed with exit code 70 (use -v to see invocation)
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
clang: note: diagnostic msg: Error generating preprocessed source(s) - cannot generate preprocessed source with multiple -arch options.
make[2]: *** [_deps/highway-build/CMakeFiles/mask_combine_test.dir/hwy/tests/mask_combine_test.cc.o] Error 70
make[1]: *** [_deps/highway-build/CMakeFiles/mask_combine_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
fatal error: error in backend: Cannot select: 0x7fcd4a3eb008: v8i16 = X86ISD::VZEXT_MOVL 0x7fcd42cf2ae0, highway-src/hwy/ops/x86_128-inl.h:3229:13 @[ highway-src/hwy/ops/x86_128-inl.h:3254:10 @[ highway-src/hwy/ops/x86_128-inl.h:7199:10 @[ highway-src/hwy/ops/generic_ops-inl.h:1313:8 @[ highway-src/hwy/tests/interleaved_test.cc:145:5 ] ] ] ]
  0x7fcd42cf2ae0: v8i16 = bitcast 0x7fcd42dfe540, highway-src/hwy/ops/x86_128-inl.h:2177:21 @[ highway-src/hwy/tests/interleaved_test.cc:138:24 ]
    0x7fcd42dfe540: v4i32 = scalar_to_vector 0x7fccd2263e70, highway-src/hwy/ops/x86_128-inl.h:2177:21 @[ highway-src/hwy/tests/interleaved_test.cc:138:24 ]
      0x7fccd2263e70: i32,ch = load<(load (s32) from %ir.133, align 2, !alias.scope !618053, !noalias !618058)> 0x7fcd4a3f1a98, 0x7fcd4a3e9d08, undef:i64, highway-src/hwy/base.h:340:3 @[ highway-src/hwy/ops/x86_128-inl.h:2176:3 @[ highway-src/hwy/tests/interleaved_test.cc:138:24 ] ]
        0x7fcd4a3e9d08: i64 = add nuw 0x7fcd4a3c6f00, Constant:i64<12>, /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/__memory/unique_ptr.h:506:12 @[ highway-src/hwy/tests/interleaved_test.cc:133:7 ]
          0x7fcd4a3c6f00: i64,ch = CopyFromReg 0x7fcd40a3bb18, Register:i64 %2, highway-src/hwy/aligned_allocator.h:195:10 @[ highway-src/hwy/aligned_allocator.h:255:7 @[ highway-src/hwy/aligned_allocator.h:262:10 @[ highway-src/hwy/tests/interleaved_test.cc:127:15 ] ] ]
            0x7fcd4a3eee00: i64 = Register %2
          0x7fccd2261aa0: i64 = Constant<12>
        0x7fcd42cf28d8: i64 = undef
In function: _ZN3hwy10N_AVX3_SPR25TestLoadStoreInterleaved4clIsNS0_4SimdIsLm2ELi0EEEEEvT_T0_
clang: error: clang frontend command failed with exit code 70 (use -v to see invocation)
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
clang: note: diagnostic msg: Error generating preprocessed source(s) - cannot generate preprocessed source with multiple -arch options.
make[2]: *** [_deps/highway-build/CMakeFiles/interleaved_test.dir/hwy/tests/interleaved_test.cc.o] Error 70
make[1]: *** [_deps/highway-build/CMakeFiles/interleaved_test.dir/all] Error 2

OS environment: macos 12.7.6
step to produce:
1. cmake ..
2. make -j 4

**Comment by KumarGitesh2024** [comment]
Hi @cedricnew92 
Could you let us know which version of Gemma you are facing challenges as well as the variation(PT or IT) and also let us know the steps you are performing?

**Comment by cedricnew92** [comment]
Hello Kumar,

I'm using version v0.1.2 (latest version). I was just trying to build the repo without any changes, and it hit this error during the building process.
Steps:
1. git clone https://github.com/google/gemma.cpp.git
2. cd build
3. cmake ..
4. make -j 4

it hit this error somewhere linking the executable test/if_test
<img width="1439" alt="Screenshot 2024-09-18 at 3 04 41 PM" src="https://github.com/user-attachments/assets/3d3b95eb-d72f-485f-a5a6-b807fca35876">

It look like originated from highway-src.

Thanks for responding on my issue.

**Comment by jan-wassenberg** [comment]
Hi @cedricnew92 , this is strange, the code being compiled and error message relate to x86 , but the compiler's version mentions arm64-apple-darwin21.6.0. 
It looks like you are using the compiler provided by XCode. As a first step, is it possible for you to update XCode? Can you share the CMake output, after `rm -rf build`? 
It builds fine for me with Apple clang version 15.0.0 (clang-1500.3.9.4).

**Comment by cedricnew92** [comment]
I've changed my build to make -j 4 gemma and it running fine now. Thanks for the prompt response! you can close this issue now.
