### ISSUE TITLE
How to make gemma support Chinese?

### ISSUE THREAD

**Issue by ogres-roar** [google/gemma.cpp#44]
how to make gemma support Chinese?
I just use gemma on ollama, and find that it only support english.
it's difficult for Chinese to use gemma.
could I do some thing to make it support chinese.
I only have a rtx4090, 64GB RAM and i9 cpu.

**Comment by ogres-roar** [comment]
some example:

<img width="1504" alt="image" src="https://github.com/google/gemma.cpp/assets/105896769/4480d397-4f65-49d8-9173-9af18f59c7e1">

  __ _  ___ _ __ ___  _ __ ___   __ _   ___ _ __  _ __
 / _` |/ _ \ '_ ` _ \| '_ ` _ \ / _` | / __| '_ \| '_ \
| (_| |  __/ | | | | | | | | | | (_| || (__| |_) | |_) |
 \__, |\___|_| |_| |_|_| |_| |_|\__,_(_)___| .__/| .__/
  __/ |                                    | |   | |
 |___/                                     |_|   |_|

tokenizer                     : 7b-pt-sfp/tokenizer.spm
compressed_weights            : 7b-pt-sfp/7b-pt-sfp.sbs
model                         : 7b-pt
weights                       : [no path specified]
max_tokens                    : 3072
max_generated_tokens          : 2048

**Comment by ogres-roar** [comment]
<img width="1511" alt="image" src="https://github.com/google/gemma.cpp/assets/105896769/c0a2b0ab-b7da-49be-8ff8-f3b1c916a653">

the response wouldn't stop, it will be always print the same content "课程内容非常全面".

**Comment by ogres-roar** [comment]
<img width="1508" alt="image" src="https://github.com/google/gemma.cpp/assets/105896769/17df4152-ad92-434f-9d20-2a30e5b9a9db">

tokenizer                     : 2b-pt-sfp/tokenizer.spm
compressed_weights            : 2b-pt-sfp/2b-pt-sfp.sbs
model                         : 2b-pt
weights                       : [no path specified]
max_tokens                    : 3072
max_generated_tokens          : 2048

the same as english. it will repeat "he United States is a country of many languages, with English being the most widely spoken language. The United States is a country of many religions, with Christianity being the most widely practiced religion. The United States is a country of many ethnicities, with many different ethnicities living in the country."

**Comment by austinvhuang** [comment]
Hi @ogres-roar - couple pointers:

- there are other forums (eg see discord link https://ai.google.dev/gemma/?utm_source=keyword&utm_medium=referral&utm_campaign=gemma_cta&utm_content) to discuss the model itself

- have a look at the model card here https://www.kaggle.com/models/google/gemma/ - gemma is primarily trained on english corpuses. the tokenizer has a large vocabulary so if you're interested you might explore what's possible with fine tuning in spite of that.

- for interacting with the model, you generally probably want to use the -it "instruction tuned" models, not the -pt "pretrained" models

**Comment by ogres-roar** [comment]
thanks a lot

**Comment by freefer** [comment]
> thanks a lot非常感谢

所以你咋解决这个

**Comment by ycjcl868** [comment]
Maybe you need this [Gemma-1.1-7B-Chinese-Chat](https://huggingface.co/ycjcl868/Gemma-1.1-7B-Chinese-Chat)
