### ISSUE TITLE
compile problems

### ISSUE THREAD

**Issue by bigbigzxl** [google/gemma.cpp#48]
compiled in linux:
Linux  x86_64 x86_64 x86_64 GNU/Linux
![image](https://github.com/google/gemma.cpp/assets/25808190/f18c7f5d-7ed7-4821-a043-56f565c04211)

**Comment by jan-wassenberg** [comment]
Hi, it looks like your compiler would require an update, it is too old. I'm curious which version it is?

**Comment by bigbigzxl** [comment]
hi, jan, ths for your replay.
my compiler version is : gcc (GCC) 12.0.1 20220220 (experimental)

**Comment by jan-wassenberg** [comment]
Thanks, the compiler is recent enough. It seems that binutils (gas) is too old. Version 2.3 from 2018 would be required.

**Comment by bigbigzxl** [comment]
yes, mine binutils Version is 2.28;
i will try to upgrate first, ths

**Comment by esrrhs** [comment]
same problem, after upgrade binutils, compile ok

**Comment by austinvhuang** [comment]
@esrrhs thanks for reporting. Will close for now but @bigbigzxl if upgrading binutils doesn't resolve this for you, can post here + reopen.
