### ISSUE TITLE
How to open PROFILER_ZONE to see the hwy profiling results?

### ISSUE THREAD

**Issue by jiaxiyang** [google/gemma.cpp#73]
https://github.com/google/gemma.cpp/blob/ae7901c3f441d70b54bb78d11d040c9a9c81ab94/gemma.cc#L286

**Comment by jan-wassenberg** [comment]
Hi, you can build with `-DPROFILER_ENABLED=1`, then use %q at the prompt to quit, and we print the results to stdout.

**Comment by jiaxiyang** [comment]
> Hi, you can build with `-DPROFILER_ENABLED=1`, then use %q at the prompt to quit, and we print the results to stdout.

Thanks!
