### ISSUE TITLE
Running make -j4 gemma fails on android termux

### ISSUE THREAD

**Issue by agchaowanhui** [google/gemma.cpp#80]
![123](https://github.com/google/gemma.cpp/assets/48917676/80cdfd9c-cef8-4c3c-bd04-6abfe7d43d46)

I tried make gemma also this fails, what causes this?

**Comment by jan-wassenberg** [comment]
Has anyone seen such an error before?
I see [similar](https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/819) [reports](https://github.com/ros-planning/moveit2_tutorials/issues/541) but no solution.

**Comment by agchaowanhui** [comment]
It seems to be the file system, I have android 14, is the success a lower android version? Not sure what to change at the moment.
