### ISSUE TITLE
Building android executables on ubuntu

### ISSUE THREAD

**Issue by agchaowanhui** [google/gemma.cpp#84]
After executing the command "cmake -DCMAKE_TOOLCHAIN_FILE=/usr/lib/android-sdk/ndk/25.1.8937393/build/cmake/android.toolchain.cmake -B build- android" and after it succeeded I ran "make -j 4 gemma" and got the following error

![image](https://github.com/google/gemma.cpp/assets/48917676/512f9d56-4435-4677-8c66-e6bc32516650)

How do I fix it?

**Comment by jan-wassenberg** [comment]
Thanks for reporting. You can safely comment out that line. We will also change the code to avoid it on older Android (<r21).

**Comment by agchaowanhui** [comment]
Okay, thanks.
