### ISSUE TITLE
project does not work as submodule

### ISSUE THREAD

**Issue by bachittle** [google/gemma.cpp#88]
steps to reproduce issue:

take a look at my minimal example: https://github.com/bachittle/test-gemma-submodule . I add gemma.cpp as a subdirectory and compile it. The main executable is now in the build folder alongside libgemma. But when I try to run it, it does not go past the "reading prompt" stage. This is unusual, as even that executable should behave the same as if compiled directly. So I am unsure of what the issue is. This also shows up in my own repository when initializing and calling the GenerateGemma function, so that may be where the issue arises.

**Comment by bachittle** [comment]
I figured out the issue. The project must compile in Release mode, it does not work in Debug. Is this something that can or should be fixed or documented? Sometimes it is useful to compile things in Debug mode. I will close issue.

**Comment by jan-wassenberg** [comment]
Glad you've found the issue. With SIMD code, unfortunately debug builds are about 100x slower and thus not usable. The minimum optimization flags required are for inlining. Personally, I get more value from asan and msan builds; we also enable our debug-only asserts there.
