### ISSUE TITLE
Compile error on visual studio build, array size exceed

### ISSUE THREAD

**Issue by insooneelife** [google/gemma.cpp#90]
I performed the build like this:
cmake --build --preset make -j 1

Then the following compilation error occurred:
error C2148:
Total size of array must not exceed 0x7fffffff bytes.

After looking into it, it seems that it is impossible to load more than 2GB in Windows.

**Comment by jan-wassenberg** [comment]
Yes, the way the code is structured unfortunately does not work with MSVC. However, also on Windows it is possible to build using GCC or Clang compilers.

**Comment by insooneelife** [comment]
These problems were solved by building with Clang. Thank.
