### ISSUE TITLE
gemma.exe does not respond no matter how long you wait.

### ISSUE THREAD

**Issue by insooneelife** [google/gemma.cpp#91]
I built and ran gemma with Windows visual studio.

I ran gemma.exe with the following command line.
`--tokenizer tokenizer.spm --compressed_weights 2b-it-sfp.sbs --model 2b-it`

But gemma.exe does not respond no matter how long you wait.

![gemma error](https://github.com/google/gemma.cpp/assets/8437769/d0f39518-e974-4bad-a02e-26fda161d628)

Can you tell me what kind of issue this is?

**Comment by austinvhuang** [comment]
Check that the cmake build configuration is set to Release mode (or clang is set to `-O2`) - that should be the default but it's possible to override it depending on how cmake was invoked.

**Comment by insooneelife** [comment]
Since it is built using Release, it responds quickly. Thanks!

**Comment by jan-wassenberg** [comment]
:) FYI we have added another line to the printed configuration to catch this issue.
